[phases.setup]
nixPkgs = [
  "nodejs_18",
  "python3",
  "pkg-config",
  "cairo",
  "pango", 
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "fontconfig",
  "freetype",
  "gcc"
]

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start" 